### ISSUE TITLE
High Resolution Image Capture results in Out Of Memory Exception

### ISSUE THREAD

**Issue by arnav-cashify** [shiyinghan/UVCAndroid#52]
While trying to capture 4000x3000 resolution image, getting following error->

> 	java.lang.OutOfMemoryError: Failed to allocate a 192000016 byte allocation with 3983656 free bytes and 3890KB until OOM, target footprint 201326592, growth limit 201326592
> 		at com.herohan.uvcapp.CameraRendererHolder$CaptureHolder.captureImageRawData(CameraRendererHolder.java:121)
> 		at com.herohan.uvcapp.CameraRendererHolder.lambda$captureImage$2$com-herohan-uvcapp-CameraRendererHolder(CameraRendererHolder.java:60)
> 		at com.herohan.uvcapp.CameraRendererHolder$$ExternalSyntheticLambda2.run(Unknown Source:4)
> 		at android.os.Handler.handleCallback(Handler.java:942)
> 		at android.os.Handler.dispatchMessage(Handler.java:99)
> 		at android.os.Looper.loopOnce(Looper.java:226)
> 		at android.os.Looper.loop(Looper.java:313)
> 		at com.serenegiant.opengl.EGLTask.run(EGLTask.java:118)

**Comment by shiyinghan** [comment]
![image](https://github.com/shiyinghan/UVCAndroid/assets/46857559/5ed64d8c-b8af-4b6c-8747-971e2e50585b)
You can try adding ‘android:largeHeap="true"’ in AndroidManifest.xml, just like in the screenshot above
