### ISSUE TITLE
IFrameCallback的返回值ByteBuffer 的大小为0

### ISSUE THREAD

**Issue by HeLiHuang** [shiyinghan/UVCAndroid#63]
private final IFrameCallback frameCallback = new IFrameCallback() {
        @Override
        public void onFrame(ByteBuffer frame) {
            buffer.flip();
             int len = buffer.limit() - buffer.position(); // len为0
             // 这里len为0 不知道为什么？
        }
    };

**Comment by shiyinghan** [comment]
![image](https://github.com/shiyinghan/UVCAndroid/assets/46857559/a192cd60-c7ea-4fa5-b9c2-ef379ec9665d)
可以参考SetFrameCallbackActivity，长度使用remaining()函数来获取

**Comment by HeLiHuang** [comment]
谢谢，已解决
